export let foodData = [
    {
        id: 75,
        category_id: "52",
        image: "https://course.divinecoder.com/images/1727247592.jpeg",
        name: "item one",
    },
    {
        id: 66,
        category_id: "52",
        image: "https://course.divinecoder.com/images/1727246227.jpg",
        name: "chicken Fry",
        price: "300",
        rating: "99",
        rating_count: "56",
        facilities: "food",
        category_name: "Chicken Fry",
    },
    {
        id: 61,
        category_id: "47",
        image: "https://course.divinecoder.com/images/1727168621.jpeg",
        name: "shawarma",
        price: "989",
        rating: "36",
        rating_count: "23",
        facilities: "best food",
        category_name: "shawarma",
    },
    {
        id: 86,
        category_id: "51",
        image: "https://course.divinecoder.com/images/1727248426.jpg",
        name: "Tandoori Chicken",
        price: "76",
        rating: "66",
        rating_count: "666",
        facilities: "food",
        category_name: "Tandoori Chicken",
    },
    {
        id: 64,
        category_id: "47",
        image: "https://course.divinecoder.com/images/1727168901.jpeg",
        name: "shawarma",
        price: "334",
        rating: "231",
        rating_count: "34",
        facilities: "best food",
        category_name: "shawarma",
    },
    {
        id: 63,
        category_id: "47",
        image: "https://course.divinecoder.com/images/1727168857.jpeg",
        name: "shawarma",
        price: "354",
        rating: "43",
        rating_count: "23",
        facilities: "best food",
        category_name: "shawarma",
    },
    {
        id: 70,
        category_id: "48",
        image: "https://course.divinecoder.com/images/1727247108.jpg",
        name: "burger",
        price: "344",
        rating: "54",
        rating_count: "567",
        facilities: "best food",
        category_name: "burger",
    },
    {
        id: 62,
        category_id: "47",
        image: "https://course.divinecoder.com/images/1727168734.jpeg",
        name: "shawarma",
        price: "909",
        rating: "345",
        rating_count: "34",
        facilities: "food",
        category_name: "shawarma",
    },
    {
        id: 92,
        category_id: "52",
        image: "https://course.divinecoder.com/images/1727249181.jpeg",
        name: "chicken Fry",
        price: "34",
        rating: "45",
        rating_count: "67",
        facilities: "Ek glass Pani, Duta Tissue, Ekta Box, Ekta sos, Duita Camoch",
        category_name: "Chicken Fry",
    },
    {
        id: 73,
        category_id: "44",
        image: "https://course.divinecoder.com/images/1727247474.jpg",
        name: "spring rools",
        price: "34",
        rating: "54",
        rating_count: "678",
        facilities: "Its testfull",
        category_name: "Spring rools",
    },
];
